name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Upload test binaries
      uses: actions/upload-artifact@v4
      with:
        name: test-binaries
        path: ./BackEndAutomation/bin/Release/net8.0/

  test:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Download test binaries
      uses: actions/download-artifact@v4
      with:
        name: test-binaries
        path: ./build-output

    - name: List downloaded files (for debug)
      run: dir ./build-output

    - name: Run Tests
      run: dotnet test ./build-output/BackEndAutomation.dll --logger "trx"
