name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build test project
        run: dotnet build /BackEndAutomation/BackEndAutomation.csproj --configuration Release --no-restore

      - name: List compiled files
        run: dir .\BackEndAutomation\bin\Release\net8.0

      - name: Upload test binaries
        uses: actions/upload-artifact@v4
        with:
          name: test-binaries
          path: ./BackEndAutomation/bin/Release/net8.0/

  test:
    runs-on: windows-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Download test binaries
        uses: actions/download-artifact@v4
        with:
          name: test-binaries
          path: ./test-binaries

      - name: Run Tests
        run: dotnet test ./test-binaries/BackEndAutomation.dll --logger "trx"
