name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Upload build output
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: ./BackEndAutomation/bin/Release/net8.0/

  test:
    runs-on: windows-latest
    needs: build

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Download build output
      uses: actions/download-artifact@v4
      with:
        name: build-output

    - name: Run Tests
      run: dotnet test ./BackEndAutomation.dll --no-build --configuration Release --logger "trx"
